### ISSUE TITLE
(Ionic 4.0.0, ionic-native 5) GoogleMapsEvent.MAP_READY not fired

### ISSUE THREAD

**Issue by francovp** [ionic-team/ionic-native-google-maps#162]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-googlemaps 2.5.0-beta-20190102-1842 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.10 "Diagnostic"
phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

"@ionic-native/core": "^5.0.0", "@ionic-native/google-maps": "^5.0.0-beta.26",

**Current behavior:**

The `GoogleMapsEvent.MAP_READY` event never gets fired.

**Expected behavior:**

**Related code, data or error log (please format your code or data):**

```
this.map = await GoogleMaps.create('map_canvas_details', mapOptions);

        console.log("Creating map");

      // Wait the MAP_READY before using any methods.

        this.map.one(GoogleMapsEvent.MAP_READY).then( async () => {
          console.log("Map ready");
          resolve();
        }).catch((error) => {
          console.error(error);
          reject(error);
        });
```

The "Map Ready" log never get printed and the promise never gets resolved

**Comment by wf9a5m75** [comment]
Please try `2.5.0-beta-20190123-2007` at least.

**Comment by wf9a5m75** [comment]
```
this.map = await GoogleMaps.create('map_canvas_details', mapOptions);
```

GoogleMaps.create() returns as synchronize.

**Comment by francovp** [comment]
I update the plugin to cordova-plugin-googlemaps `2.5.0-beta-20190124-1620` and remove the await from `this.map = await GoogleMaps.create('map_canvas_details', mapOptions);` but it doesn't make any difference :/

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub repository

**Comment by wf9a5m75** [comment]
Github provides free secret repository for everyone.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since you don't share any program, I can not confirm the problem, but probably the problem is fix.

**Comment by francovp** [comment]
Sorry for the late response. I will try the fix you make and will comment. Question: for Ionic 4 I need to use the master branch now? or multiple_maps branch? 

If it doesn't work I will share the project with you

**Comment by wf9a5m75** [comment]
v5 branch

**Comment by francovp** [comment]
It's ok to reference it like this in package.json ?
`    "@ionic-native/google-maps": "git+https://github.com/ionic-team/ionic-native-google-maps.git#v5"`

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/ionic-googlemaps-quickdemo-v4/blob/master/src/app/home/home.page.ts

**Comment by francovp** [comment]
So, that demo show I have to use `@ionic-native/google-maps` but the PPT tutorial says that I need to import from `@ionic-native/google-maps/ngx`
Ok

**Comment by wf9a5m75** [comment]
`@ionic-native/google-maps` should be enough.

**Comment by francovp** [comment]
I'm getting 
`ERROR in src/app/home/home.module.ts(5,28): error TS2307: Cannot find module '@ionic-native/google-maps'.
src/app/home/home.page.ts(15,8): error TS2307: Cannot find module '@ionic-native/google-maps'.`

now :/

I add you to my private project, can you check it please?

**Comment by wf9a5m75** [comment]
For private repo support, please donate $5 to the project for maps plugin activity.

**Comment by wf9a5m75** [comment]
Thank you for your donation. I investigated your code, and there were many problems, not this plugin's problem.
I committed to your repo.

![screen shot 2019-02-13 at 3 26 42 pm](https://user-images.githubusercontent.com/167831/52756037-eee34000-2fb4-11e9-8369-8508390df031.png)
![android](https://user-images.githubusercontent.com/167831/52756046-f6a2e480-2fb4-11e9-9677-085aef495b18.png)
![screen shot 2019-02-13 at 5 29 56 pm](https://user-images.githubusercontent.com/167831/52756054-01f61000-2fb5-11e9-82c5-b5899c2e0315.png)

**Comment by francovp** [comment]
Hi, thank you very much for your help :) I really appreciate it because this was stopping me progress for weeks. 

I pull your commits but I still receiving the same errors that I mention [here ](https://github.com/ionic-team/ionic-native-google-maps/issues/162#issuecomment-461402974) when I run `ionic cordova build ios`

I run npm install and nothing changes :/ So I can't build the project.
Any idea was is going on?

**Comment by wf9a5m75** [comment]
I did just `npm install`

**Comment by wf9a5m75** [comment]
Try this steps.


https://github.com/ionic-team/ionic-native-google-maps/issues/167#issuecomment-462157627

**Comment by francovp** [comment]
Works with version `5.0.0-beta.26`. I don't now why the v5 branch doesn't work, but I will try that

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Please reinstall 
- `cordova-plugin-googlemaps` v2.5.1
- `@ionic-native/google-maps` v5.0.0-beta.27

**Comment by francovp** [comment]
Works pretty well with those versions :) Now is rendering the overlay correctly in my side.
So my issue is solved :D 

Thank you very much!
